import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>ChessonChain</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header />
      </main>
    </>
  );
}

const Header = () => {
  return (
    <header>
      <div className='ellipse'></div>
      <h1>P2E MULTI-CHAIN/INTER-CHAIN CHESS GAME</h1>
      <p>
        Play and earn in an exciting multi-chain NFT chess game for chess and
        blockchain enthusiasts.
      </p>
      <a href='#'>
        <button className='green'>Play game</button>
      </a>
    </header>
  );
};
